# Generated by Django 3.1.4 on 2020-12-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneluxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='p_image',
            field=models.ImageField(default='default-image.png', upload_to='projects'),
        ),
    ]
