# Generated by Django 3.1.4 on 2020-12-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneluxapp', '0002_auto_20201206_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p_title',
            field=models.CharField(default='pto title ', max_length=150),
            preserve_default=False,
        ),
    ]
