# Generated by Django 3.1.4 on 2020-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneluxapp', '0003_projects_p_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
    ]
