# Generated by Django 3.1.4 on 2020-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneluxapp', '0004_projects_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='over_para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
    ]
